name: recipe_app_fourtitude_jw
description: "Recipe App for the Fourtitude.asia test."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pull_to_refresh_flutter3: ^2.0.2
  provider: ^6.1.5
  go_router: ^15.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  form_builder_image_picker: ^4.3.1
  image_picker: ^1.1.2
  flutter_filter_dialog: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/recipeTypes.json
    - assets/images/